version: "3"
services:
  fhir:
    image: hapiproject/hapi:latest
    ports:
      - "8080:8080"
    environment:
      HAPI_FHIR_DB_HOST: fhir-db
      HAPI_FHIR_DB_PORT: 5432
      HAPI_FHIR_DB_NAME: hapi_r4
      HAPI_FHIR_DB_USER: admin
      HAPI_FHIR_DB_PASS: admin

  fhir-db:
    image: postgres
    volumes:
      - fhir-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi_r4

volumes:
  fhir-db-data:

